<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PersonasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('personas')->insert([
            ['rut' => '12.345.678-9', 'nombre_usuario' => 'juanperez', 'nombres' => 'Juan', 'primer_apellido' => 'Pérez', 'segundo_apellido' => 'González', 'supervisor' => 'Ana López', 'empresa' => 'Empresa A', 'estado_empleado' => 1, 'centro_costo' => 'Centro A', 'denominacion' => 'Administrador', 'titulo_puesto' => 'Gerente de TI', 'fecha_inicio' => '2020-01-15', 'usuario_ti' => 1, 'ubicacion' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '98.765.432-1', 'nombre_usuario' => 'marialopez', 'nombres' => 'María', 'primer_apellido' => 'López', 'segundo_apellido' => 'Rodríguez', 'supervisor' => 'Carlos Martínez', 'empresa' => 'Empresa B', 'estado_empleado' => 1, 'centro_costo' => 'Centro B', 'denominacion' => 'Secretaria', 'titulo_puesto' => 'Asistente Ejecutivo', 'fecha_inicio' => '2019-03-22', 'usuario_ti' => 0, 'ubicacion' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '15.456.789-0', 'nombre_usuario' => 'pedrohernandez', 'nombres' => 'Pedro', 'primer_apellido' => 'Hernández', 'segundo_apellido' => 'Méndez', 'supervisor' => 'Juan Pérez', 'empresa' => 'Empresa C', 'estado_empleado' => 1, 'centro_costo' => 'Centro C', 'denominacion' => 'Consultor', 'titulo_puesto' => 'Consultor de Proyectos', 'fecha_inicio' => '2021-05-10', 'usuario_ti' => 0, 'ubicacion' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '23.876.543-2', 'nombre_usuario' => 'luciasanchez', 'nombres' => 'Lucía', 'primer_apellido' => 'Sánchez', 'segundo_apellido' => 'Vega', 'supervisor' => 'Ana López', 'empresa' => 'Empresa D', 'estado_empleado' => 1, 'centro_costo' => 'Centro D', 'denominacion' => 'Contadora', 'titulo_puesto' => 'Contadora General', 'fecha_inicio' => '2020-11-05', 'usuario_ti' => 0, 'ubicacion' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '67.432.109-8', 'nombre_usuario' => 'carlosgarcia', 'nombres' => 'Carlos', 'primer_apellido' => 'García', 'segundo_apellido' => 'Martínez', 'supervisor' => 'Pedro Hernández', 'empresa' => 'Empresa E', 'estado_empleado' => 1, 'centro_costo' => 'Centro E', 'denominacion' => 'Gerente', 'titulo_puesto' => 'Director de Operaciones', 'fecha_inicio' => '2018-02-19', 'usuario_ti' => 1, 'ubicacion' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '12.678.432-0', 'nombre_usuario' => 'luiscastro', 'nombres' => 'Luis', 'primer_apellido' => 'Castro', 'segundo_apellido' => 'Moreno', 'supervisor' => 'Carlos Martínez', 'empresa' => 'Empresa F', 'estado_empleado' => 1, 'centro_costo' => 'Centro F', 'denominacion' => 'Vendedor', 'titulo_puesto' => 'Representante de Ventas', 'fecha_inicio' => '2021-07-23', 'usuario_ti' => 0, 'ubicacion' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '45.213.876-3', 'nombre_usuario' => 'sofiaferrari', 'nombres' => 'Sofía', 'primer_apellido' => 'Ferrari', 'segundo_apellido' => 'Ruiz', 'supervisor' => 'Juan Pérez', 'empresa' => 'Empresa G', 'estado_empleado' => 1, 'centro_costo' => 'Centro G', 'denominacion' => 'Técnico', 'titulo_puesto' => 'Técnico de Soporte', 'fecha_inicio' => '2022-04-02', 'usuario_ti' => 0, 'ubicacion' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '34.567.890-1', 'nombre_usuario' => 'ricardodíaz', 'nombres' => 'Ricardo', 'primer_apellido' => 'Díaz', 'segundo_apellido' => 'Romero', 'supervisor' => 'Ana López', 'empresa' => 'Empresa H', 'estado_empleado' => 1, 'centro_costo' => 'Centro H', 'denominacion' => 'Diseñador', 'titulo_puesto' => 'Diseñador Gráfico', 'fecha_inicio' => '2020-06-14', 'usuario_ti' => 1, 'ubicacion' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '56.789.012-3', 'nombre_usuario' => 'margaritaperez', 'nombres' => 'Margarita', 'primer_apellido' => 'Pérez', 'segundo_apellido' => 'Vásquez', 'supervisor' => 'Carlos Martínez', 'empresa' => 'Empresa I', 'estado_empleado' => 1, 'centro_costo' => 'Centro I', 'denominacion' => 'Abogado', 'titulo_puesto' => 'Asesor Legal', 'fecha_inicio' => '2019-09-10', 'usuario_ti' => 0, 'ubicacion' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '78.234.567-8', 'nombre_usuario' => 'danieljimenez', 'nombres' => 'Daniel', 'primer_apellido' => 'Jiménez', 'segundo_apellido' => 'Figueroa', 'supervisor' => 'Juan Pérez', 'empresa' => 'Empresa J', 'estado_empleado' => 1, 'centro_costo' => 'Centro J', 'denominacion' => 'Programador', 'titulo_puesto' => 'Desarrollador de Software', 'fecha_inicio' => '2021-02-28', 'usuario_ti' => 1, 'ubicacion' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '90.123.456-7', 'nombre_usuario' => 'julianamendez', 'nombres' => 'Juliana', 'primer_apellido' => 'Méndez', 'segundo_apellido' => 'González', 'supervisor' => 'Ana López', 'empresa' => 'Empresa K', 'estado_empleado' => 1, 'centro_costo' => 'Centro K', 'denominacion' => 'Marketing', 'titulo_puesto' => 'Especialista en Marketing', 'fecha_inicio' => '2020-04-11', 'usuario_ti' => 0, 'ubicacion' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '34.123.987-5', 'nombre_usuario' => 'alejandromoreno', 'nombres' => 'Alejandro', 'primer_apellido' => 'Moreno', 'segundo_apellido' => 'Ruiz', 'supervisor' => 'Carlos Martínez', 'empresa' => 'Empresa L', 'estado_empleado' => 1, 'centro_costo' => 'Centro L', 'denominacion' => 'Técnico', 'titulo_puesto' => 'Técnico de Redes', 'fecha_inicio' => '2021-06-19', 'usuario_ti' => 1, 'ubicacion' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '12.987.654-3', 'nombre_usuario' => 'veronicavilches', 'nombres' => 'Verónica', 'primer_apellido' => 'Vilches', 'segundo_apellido' => 'Alvarado', 'supervisor' => 'Juan Pérez', 'empresa' => 'Empresa M', 'estado_empleado' => 1, 'centro_costo' => 'Centro M', 'denominacion' => 'Gerente', 'titulo_puesto' => 'Directora de Finanzas', 'fecha_inicio' => '2018-01-22', 'usuario_ti' => 0, 'ubicacion' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '65.432.109-7', 'nombre_usuario' => 'martinlopez', 'nombres' => 'Martín', 'primer_apellido' => 'López', 'segundo_apellido' => 'Paredes', 'supervisor' => 'Ana López', 'empresa' => 'Empresa N', 'estado_empleado' => 1, 'centro_costo' => 'Centro N', 'denominacion' => 'Director', 'titulo_puesto' => 'Director de Tecnología', 'fecha_inicio' => '2017-11-01', 'usuario_ti' => 1, 'ubicacion' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '87.654.321-0', 'nombre_usuario' => 'catalinagonzalez', 'nombres' => 'Catalina', 'primer_apellido' => 'González', 'segundo_apellido' => 'Fernández', 'supervisor' => 'Carlos Martínez', 'empresa' => 'Empresa O', 'estado_empleado' => 1, 'centro_costo' => 'Centro O', 'denominacion' => 'Operario', 'titulo_puesto' => 'Operaria de Producción', 'fecha_inicio' => '2020-08-13', 'usuario_ti' => 0, 'ubicacion' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '23.456.789-4', 'nombre_usuario' => 'sergioalonso', 'nombres' => 'Sergio', 'primer_apellido' => 'Alonso', 'segundo_apellido' => 'Lozano', 'supervisor' => 'Juan Pérez', 'empresa' => 'Empresa P', 'estado_empleado' => 1, 'centro_costo' => 'Centro P', 'denominacion' => 'Logística', 'titulo_puesto' => 'Jefe de Logística', 'fecha_inicio' => '2021-09-28', 'usuario_ti' => 1, 'ubicacion' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '65.456.789-9', 'nombre_usuario' => 'paulafernandez', 'nombres' => 'Paula', 'primer_apellido' => 'Fernández', 'segundo_apellido' => 'Cordero', 'supervisor' => 'Carlos Martínez', 'empresa' => 'Empresa Q', 'estado_empleado' => 1, 'centro_costo' => 'Centro Q', 'denominacion' => 'Comercial', 'titulo_puesto' => 'Ejecutiva Comercial', 'fecha_inicio' => '2021-10-17', 'usuario_ti' => 0, 'ubicacion' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['rut' => '45.345.678-0', 'nombre_usuario' => 'danielmora', 'nombres' => 'Daniel', 'primer_apellido' => 'Mora', 'segundo_apellido' => 'Vargas', 'supervisor' => 'Ana López', 'empresa' => 'Empresa R', 'estado_empleado' => 1, 'centro_costo' => 'Centro R', 'denominacion' => 'Técnico', 'titulo_puesto' => 'Ingeniero de Soporte', 'fecha_inicio' => '2020-06-28', 'usuario_ti' => 1, 'ubicacion' => 5, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
